import type { Metadata } from "next";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Terms of Service | CompliVibe",
  description: "CompliVibe Terms of Service — governing your use of the EU AI Act and India DPDP compliance platform.",
  alternates: { canonical: "https://complivibe.in/legal/terms" },
  openGraph: {
    title: "Terms of Service | CompliVibe",
    description: "Terms governing your use of CompliVibe, the AI compliance platform for Indian companies.",
    url: "https://complivibe.in/legal/terms",
    images: [{ url: "https://complivibe.in/og-placeholder.png", width: 1200, height: 630 }],
  },
};

const sections = [
  {
    title: "1. Acceptance",
    content: `By creating an account or using the CompliVibe platform (the "Service"), you agree to be bound by these Terms of Service ("Terms"). If you are using the Service on behalf of a company or other legal entity, you represent that you have authority to bind that entity to these Terms.

These Terms constitute a binding legal agreement between you (or your organisation) and ValersAI Connect Pvt. Ltd. ("CompliVibe", "we", "us"). If you do not agree to these Terms, do not use the Service.`,
  },
  {
    title: "2. Use of service",
    content: `CompliVibe provides a software-as-a-service platform for AI compliance management, including EU AI Act obligation mapping, India DPDP compliance tracking, and Annex IV technical documentation generation.

You may use the Service only for lawful purposes and in accordance with these Terms. You agree not to: (a) use the Service to provide compliance advice as a regulated legal or professional service without appropriate authorisation; (b) reverse engineer, decompile, or attempt to extract the source code of any part of the Service; (c) use the Service to process data in violation of applicable law; (d) share account credentials or access with unauthorised third parties; or (e) use the Service for any fraudulent or misleading purpose.

The compliance outputs generated by CompliVibe are informational tools to support your compliance programme. They do not constitute legal advice. We recommend you engage qualified legal counsel for final compliance decisions.`,
  },
  {
    title: "3. Intellectual property",
    content: `CompliVibe and its licensors own all right, title, and interest in the platform, including the obligation database, cross-mapping engine, documentation templates, and all underlying technology. These Terms do not grant you any rights to CompliVibe's intellectual property beyond the limited right to use the Service as described herein.

Your data — AI system descriptions, compliance evidence, and any proprietary information you upload — remains yours. You grant CompliVibe a limited licence to process your data to provide the Service. We do not use your data to train or improve third-party AI models.`,
  },
  {
    title: "4. Limitation of liability",
    content: `To the maximum extent permitted by applicable law, CompliVibe shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or related to your use of the Service, including but not limited to regulatory fines, lost profits, or business interruption.

CompliVibe's total cumulative liability to you for any claims arising under these Terms shall not exceed the amount paid by you for the Service in the three (3) months preceding the event giving rise to the claim.

This limitation applies regardless of the form of action and whether CompliVibe has been advised of the possibility of such damages. Some jurisdictions do not allow certain limitations of liability — in those jurisdictions, our liability is limited to the maximum extent permitted by law.`,
  },
  {
    title: "5. Governing law",
    content: `These Terms are governed by and construed in accordance with the laws of India, without regard to its conflict of law principles. Any dispute arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts of Gurugram, Haryana, India.

For EU customers: Nothing in these Terms limits your rights under mandatory EU consumer protection law or the EU AI Act applicable to our Service. We acknowledge our obligations as an AI system provider under applicable EU law.`,
  },
  {
    title: "6. Contact",
    content: `For questions about these Terms, contact:

CompliVibe (ValersAI Connect Pvt. Ltd.)
Email: legal@complivibe.in
Location: Gurugram, Haryana, India

We may update these Terms from time to time. Material changes will be notified via email to registered account holders at least 14 days before they take effect.`,
  },
];

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-black text-white">
      <Nav />
      <main className="mx-auto max-w-[800px] px-6 py-24">
        <div className="mb-12">
          <div className="text-xs text-[#555] mb-3">Last updated: May 2026</div>
          <h1
            className="text-white mb-4"
            style={{ fontSize: "clamp(2rem, 5vw, 3rem)", lineHeight: "1.1", fontWeight: "700", letterSpacing: "-0.03em" }}
          >
            Terms of Service
          </h1>
          <p className="text-[#888] leading-relaxed">
            These terms govern your access to and use of CompliVibe, the AI compliance platform operated by ValersAI Connect Pvt. Ltd. Please read them carefully before using the service.
          </p>
        </div>

        <div className="flex flex-col gap-10">
          {sections.map((s) => (
            <section key={s.title} className="border-t border-white/[0.06] pt-8">
              <h2 className="text-white font-semibold text-lg mb-4">{s.title}</h2>
              {s.content.split("\n\n").map((para, i) => (
                <p key={i} className="text-[#888] text-sm leading-relaxed mb-3 last:mb-0">
                  {para}
                </p>
              ))}
            </section>
          ))}
        </div>
      </main>
      <Footer />
    </div>
  );
}
