import {
  BookOpen,
  Layers,
  ClipboardCheck,
  Archive,
  Globe,
  GitCommit,
  Rocket,
  Boxes,
  Network,
  Plug,
  FileBarChart,
  Compass,
  ShieldCheck,
  Workflow,
  UserCheck,
  Lock,
  FileText,
  Activity,
  KeyRound,
  AlertTriangle,
  Sparkles,
  Heart,
  Brain,
  SlidersHorizontal,
  Eye,
  MessageSquare,
  LifeBuoy,
  Handshake,
  HeartPulse,
  TrendingUp,
  Cloud,
  type LucideIcon,
} from "lucide-react";

/**
 * String → icon map so server components can pass an icon by name
 * (functions cannot be passed across the server/client boundary).
 */
export const iconRegistry: Record<string, LucideIcon> = {
  BookOpen,
  Layers,
  ClipboardCheck,
  Archive,
  Globe,
  GitCommit,
  Rocket,
  Boxes,
  Network,
  Plug,
  FileBarChart,
  Compass,
  ShieldCheck,
  Workflow,
  UserCheck,
  Lock,
  FileText,
  Activity,
  KeyRound,
  AlertTriangle,
  Sparkles,
  Heart,
  Brain,
  SlidersHorizontal,
  Eye,
  MessageSquare,
  LifeBuoy,
  Handshake,
  HeartPulse,
  TrendingUp,
  Cloud,
};

export type IconName = keyof typeof iconRegistry;
